import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import Player from "@/components/player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex text-neutral-400">
          <Sidebar />
          <div className="flex flex-col w-full h-full">
            <Header />
            <div className="flex-grow h-full bg-neutral-950 pr-2 pb-1">
              <div className="bg-neutral-900 rounded-lg h-full flex flex-col justify-between">
                <div className=" rounded-lg bg-neutral-900 "></div>
                <div className=" rounded-lg h-full ">{children}</div>
                <Player />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
